### PR TITLE
Receive target location from a phone app

### PR DESCRIPTION
**Pull request by bcaller**
The Android app https://github.com/bcaller/GBIT-map-share-android allows you to share a location from the Google Maps app on Android. It opens GBIT with the destination set so you don't need to enter lat/long.

This PR allows an Android (or iPhone) app to launch GBIT with a new destination set.

It does so with the new command `insert` which receives a latitude, longitude, place name and timeline pin body text.

### CODE REVIEW

**Comment by samuelmr** [comment]
LGTM regarging C side.

Could you please refactor `function addLocation(position, extra)` a bit (it's getting quite bloated):
- move `function setTimelinePin(placeName)` outside `addLocation` (needs also `position`,as argument and copying of coords from `position` to `pos` could perhaps be done within `setTimelinePin`
- if you can, maybe also move reverse geocoding into a separate function

Please also check whitespace e.g. on lines 97..101 and 234; preferably indent with two spaces.

**Comment by samuelmr** [comment]
And if you feel like it, perhaps you could mention the Android app in `/node/views/home.handlebars` under the heading "Advanced usage" or creating separate sections for API and app.

**Comment by samuelmr** [comment]
Great work! Thanks for cleaning up my mess for me! :-)

**Comment by bcaller** [comment]
No problem. I love your app.

**Pull request merged**
